deployment:
  tasks:
    - export REPO_PATH=/home/padamtha/repositories/portfolio
    - export DEPLOY_PATH=/home/padamtha/public_html/portfolio
    - echo "Deploying to $DEPLOY_PATH"
    - cd $REPO_PATH
    - npm install
    - npm run build
    - echo "Build completed, copying files to $DEPLOY_PATH"
    - /bin/cp -r dist/* $DEPLOY_PATH/
    - echo "Deployment completed"
