deployment:
  tasks:
    - export DEPLOY_PATH=/home/padamtha/repositories/portfolio
    - echo "Deploying to $DEPLOY_PATH"
    - /bin/cp -r * $DEPLOY_PATH/
    - npm install
    - npm run build
    - echo "Build completed, copying files to $DEPLOY_PATH"
    - /bin/cp -r dist/* $DEPLOY_PATH/
    - echo "Deployment completed"
